[versions]
agp = "8.12.3"
kotlin = "2.0.21"
coreKtx = "1.16.0"

lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2024.09.00"
appcompat = "1.7.1"
material = "1.13.0"
jetbrainsKotlinJvm = "2.0.21"

daggerHilt = "2.50"
daggerHiltCompiler = "2.48.1"
andoirdxHiltNavigationCompose = "1.0.0"
kotlinAndroid = "1.8.0"
androidApplication ="8.2.0"
androidxLifecycle = "2.6.2"
androidxComposeNavigation = "2.5.0"
coil = "2.5.0"
retrofit2 = "2.9.0"
retrofit2KotlinSerialization = "1.0.0"
okhttp3 = "4.12.0"
kotlinSerializationJson = "1.6.2"
kotlinSerialization = "1.9.10"
kotlinxCoroutines = "1.7.3"
androidxRoom = "2.6.1"
androidxDatastore = "1.0.0"
androidxPreference = "1.2.1"
processPhoenix = "2.1.2"
androidxComposeCompiler = "1.5.3"
exoplayer = "1.8.0"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "daggerHilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "daggerHiltCompiler" }
hilt-core = { group = "com.google.dagger", name = "hilt-core", version.ref = "daggerHilt"}
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "andoirdxHiltNavigationCompose" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxComposeNavigation" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinSerializationJson" }
retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit2" }
retrofit2-serialization = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2KotlinSerialization" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp3" }
okhttp-url-connection = { group = "com.squareup.okhttp3", name = "okhttp-urlconnection", version.ref = "okhttp3" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp3" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
androidx-viewModel-lifecycle = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidxRoom" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidxRoom" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidxRoom" }
exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "exoplayer" }
exoplayer-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "exoplayer" }

android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }


[bundles]
retrofit2 = ["retrofit2", "retrofit2-serialization"]
okhttp3 = ["okhttp", "okhttp-url-connection", "okhttp-logging-interceptor"]
androidx-room = ["androidx-room-runtime", "androidx-room-ktx"]
androidx-ui-compose = ["androidx-ui", "androidx-ui-graphics", "androidx-ui-tooling"]
androidx-ui-compose-debug = ["androidx-ui-tooling-preview", "androidx-ui-test-manifest"]
exoplayer = ["exoplayer", "exoplayer-ui"]


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinSerialization" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "daggerHilt" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

tving-android-application = { id = "tving.android.application", version = "unspecified"}
tving-android-library = { id = "tving.android.library", version = "unspecified"}
tving-jvm-library = { id = "tving.jvm.library", version = "unspecified"}
tving-android-hilt = { id = "tving.android.hilt", version = "unspecified"}
tving-jvm-hilt = { id = "tving.jvm.hilt", version = "unspecified"}
tving-android-feature = { id = "tving.android.feature", version = "unspecified"}
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
